WEB/baroProject/accountApp/urls.py
from django.urls import path
from . import views

app_name = 'accountApp'

urlpatterns = [
    path('login/<int:usertype>', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/<int:usertype>', views.signup, name='signup'),
    path('signupAgree/', views.signupAgree, name="signupAgree"),
    path('signupSuccess/', views.signupSuccess, name="signupSuccess"),
]

WEB/baroProject/baroProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userApp.urls')),
    path('accountApp/', include('accountApp.urls')),
    path('ownerApp/', include('ownerApp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/baroProject/ownerApp/urls.py
from django.urls import path
from . import views

app_name = 'ownerApp'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('manage/', views.manage, name='manage'),
    path('register/', views.register, name='register'),
    path('register2/', views.register2, name='register2'),
    path('register3/<int:store_pk>', views.register3, name='register3'),
    path('help/', views.help, name='help'),
    path('productManage/<int:storepk>', views.productManage, name="productManage"),
]

WEB/baroProject/userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name="main"),
    path('store/', views.store, name="store"),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('addCart/<int:object_pk>', views.addCart, name='addCart'),
    path('cart/', views.cart, name='cart'),
    path('pay/', views.pay, name='pay'),
    path('accFinish', views.accFinish, name="accFinish"),
]

WEB/baroProject/ownerApp/models.py
from django.db import models
import os
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.



class Store(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    store_name = models.CharField(max_length=30)
    store_url = models.CharField(max_length=30)
    store_intro = models.TextField()
    store_tel = models.CharField(max_length=30)
    # CATEGORYLIST=[('veg', "채소/야채"), ('fruits', "과일"), ('grains', "곡류")]
    category = models.CharField( max_length=30, null=True, blank=True)
    store_address=models.CharField(max_length=100)
    # BANKLIST=[('NH', "농협"), ('KB', "국민"), ('SH', "신한"), ('etc', "기타")]
    bank = models.CharField(max_length=30, null=True, blank=True)
    account_name = models.CharField(max_length=30, null=True, blank=True)
    store_account=models.CharField(max_length=50)
    

    def __str__(self):
        return f'{self.pk} : {self.store_name} : {self.user}'


class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    name =  models.CharField(max_length=30)
    # price = models.FloatField()
    price = models.IntegerField()
    intro = models.TextField()
    Thumbnail = models.ImageField(upload_to='thumimg', null=True)
    introImage = models.ImageField(upload_to='productimg', null=True)
    salesRate = models.IntegerField(default=0, null=True)
    # OPTLIST=[('opt1', 'opt1'),('opt2', 'opt2'),('opt3', 'opt3'),('opt4', 'opt4')]
    category = models.CharField(max_length=30, null=True)
    expect = models.CharField(max_length=50, null=True)
    amount = models.CharField(max_length=30, null=True)
    expectD1 = models.DateField(null=True)
    expectD2 = models.DateField(null=True)
    deliveryD1 = models.DateField(null=True)
    deliveryD2 = models.DateField(null=True)
    # DELIERY=[("icepack","아이스팩"), ("premium", "신선배송가방")]
    deliveryOption =  models.CharField(max_length=30, null=True)
    region = models.CharField(max_length=50, null=True)

    #구매자수
    age1_M_B = models.IntegerField(null=True, default=0)
    age1_M_W = models.IntegerField(null=True, default=0)
    age1_M_G = models.IntegerField(null=True, default=0)
    age1_W_B = models.IntegerField(null=True, default=0)
    age1_W_W = models.IntegerField(null=True, default=0)
    age1_W_G = models.IntegerField(null=True, default=0)

    age2_M_B = models.IntegerField(null=True, default=0)
    age2_M_W = models.IntegerField(null=True, default=0)
    age2_M_G = models.IntegerField(null=True, default=0)
    age2_W_B = models.IntegerField(null=True, default=0)
    age2_W_W = models.IntegerField(null=True, default=0)
    age2_W_G = models.IntegerField(null=True, default=0)

    age3_M_B = models.IntegerField(null=True, default=0)
    age3_M_W = models.IntegerField(null=True, default=0)
    age3_M_G = models.IntegerField(null=True, default=0)
    age3_W_B = models.IntegerField(null=True, default=0)
    age3_W_W = models.IntegerField(null=True, default=0)
    age3_W_G = models.IntegerField(null=True, default=0)

    age4_M_B = models.IntegerField(null=True, default=0)
    age4_M_W = models.IntegerField(null=True, default=0)
    age4_M_G = models.IntegerField(null=True, default=0)
    age4_W_B = models.IntegerField(null=True, default=0)
    age4_W_W = models.IntegerField(null=True, default=0)
    age4_W_G = models.IntegerField(null=True, default=0)


    def delete(self, *args, **kwargs):
        super(Product, self).delete(*args, **kwargs)
        if self.introImage : 
            os.remove(os.path.join(settings.MEDIA_ROOT, self.introImage.path))

    def __str__(self):
        return f'{self.pk} : {self.store.store_name} : {self.name}'

# 미디어 파일 참조링크  https://wayhome25.github.io/django/2017/05/10/media-file/

WEB/baroProject/ownerApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Store, Product
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required

# Create your views here.

def main(request):
    return render(request, 'ownerApp/main.html')

@login_required
def register(request):
    return render(request, 'ownerApp/register.html')

@login_required
def register2(request):
    context={}

    if request.method == "POST":
        
        store = Store.objects.create(
            user = User.objects.get(username = request.user.get_username()) ,
            store_name = request.POST['store_name'],
            store_url = request.POST['store_url'],
            store_intro = request.POST['store_intro'],
            store_tel = request.POST['store_tel'],
            category = request.POST['category'],
            store_address = request.POST['store_address'],
            bank = request.POST['bank'],
            account_name = request.POST['account_name'],
            store_account = request.POST['store_account'] ,
        )
        print("상점이 생성되었음.")

        store_pk = store.pk
        context['store_pk'] = store_pk
        return redirect( 'ownerApp:register3', store_pk)
    else: #GET Method
        return render(request, 'ownerApp/register2.html')

def register3(request, store_pk):
    context={}
    try:
        store = Store.objects.get(pk=store_pk)
    except Store.DoesNotExist:
        print("상점 불러오기 에러")
        return redirect('userApp:home')
    context['store'] = store
    return render( request, 'ownerApp/register3.html', context)

def manage(request):
    context={}
    try:
        store = Store.objects.get(user=User.objects.get(username = request.user.get_username()))
        print(store)
    except Store.DoesNotExist:
        return redirect("ownerApp:main")
    
    products =  Product.objects.filter(store = store)[:3]
    context['products'] = products
    context['store'] = store

    return render(request, 'ownerApp/manage.html', context)

def productManage(request, storepk):
    context={}
    if request.method == "POST":
        prod = Product.objects.create(
            store = Store.objects.get(pk = storepk),
            name = request.POST['name'],
            price = request.POST['price'],
            intro = request.POST['intro_text'],
            Thumbnail = request.FILES['Thumbnail'],
            # introImage = request.POST[''],
            # salesRate = request.POST[''],
            category = request.POST['category'],
            expect = request.POST['expect'],#예상수확량
            amount = request.POST['amount'],#기준량
            expectD1 = request.POST['expectD1'],
            expectD2 = request.POST['expectD2'],
            deliveryD1 = request.POST['deliveryD1'],
            deliveryD2 = request.POST['deliveryD2'],
            deliveryOption =request.POST['deliveryOption'],
            region = request.POST['region'],
        )
        return redirect("ownerApp:manage")
    else:
        context['storepk'] = storepk
        return render(request, 'ownerApp/productManage.html', context)

def help(request):
    return HttpResponse('생산지원페이지입니다')

WEB/baroProject/ownerApp/templates/ownerApp/main.html
{% extends 'ownerbase.html' %}
{% load static %}

{% block style %}
<style>
    .background{
    /* background-color:#F5F5F5; */
    background-image: url('../../../static/img/start.jpg');
    width:1920px;
    height:1500px;
    margin-top:-550px;
    background-repeat: no-repeat;
}
.front{
    margin-left:800px;
    padding-top:450px
    
}
</style>
{% endblock %}

{% block content %}
<div class="background">
    <div class="back">
        <div class="front">
            <a href="{% url 'ownerApp:register2' %}"><img src="{% static 'img/start button.png' %}"></a>
        </div>
    </div>
</div>
{% endblock %}

WEB/baroProject/ownerApp/templates/ownerApp/manage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>솥 by SSAK3</title>
    <link rel="stylesheet" type="text/css" href="{% static 'ownerApp/manage.css' %}">
    <script src="https://kit.fontawesome.com/b0f29e9bfe.js" corssorigin="anonymous"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
<!--  -->
    <div class="wrap">
        <div class="intro">
            <div class="header">
                <ul class="nav">
                    <li><a href="{% url 'userApp:main' %}"><img src="{% static 'img/SOT_logo.png' %}"></a></li>
                    <li><a href="{% url 'userApp:store' %}">스토어</a></li>
                    <li><a href="#">커뮤니티</a></li>
                    <li><a href="#">고객센터</a></li>
                </ul>
                <ul class="searcharea">
                    {% if user.is_authenticated %}
                    <!-- 로그인 한 사용자 -->
                    <li>
                        <form action="{% url 'accountApp:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="path" value="{{request.path}}">
                            <button id = logout type = submit>Log out</a>
                        </form>
                    </li>
                    {% endif %}
                    <li><input type="search" placeholder="Serach.."></li>
                    <li><a href="{% url 'userApp:cart' %}"><img src="{% static 'img/cart.svg' %}"></a></li>
                    <li><a href="{% url 'userApp:home' %}"><img src="{% static 'img/mypage.svg' %}"></a></li>
                </ul>
            </div>
            <div class ="title">
                {% block content2 %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!--  -->
    <div style="display: flex; flex-direction: column; background-color: #f5f5f5;">
        <img src="{% static 'img/mystore.png' %}" style="margin-left: 350px; width: 350px;">
        <div class="big_container">
            <!-- 왼쪽 -->
            <div class="left_c">
                <div class="storeInfo">
                    <div id="store_title"><b>{{store.store_name}}</b></div>
                    <div id="store_cate">{{store.category}}</div>
                    <div id="store_intro">{{store.store_intro}}</div>
                </div>
                <img src="{% static 'img/sm_1.png' %}" alt="" style="width: 715px;height: 432px;">
                <img src="{% static 'img/sm_2.png' %}" alt="" style="width: 715px;height: 352px;">
                <div class="storeInfo2">
                    <div class="mimititle"><b>판매자정보</b></div>
                    <div style="padding-left: 15px;"><b>고객센터</b>   {{store.store_tel}}</div>
                    <div style="padding-left: 15px;"><b>주소</b>   {{store.store_address}}</div>
                    <div class="accInfo">
                        <b>계좌정보</b>
                        <span>{{store.bank}}</span>
                        <span>{{store.account_name}}</span>
                        <span>{{store.store_account}}</span>
                    </div>
                </div>
            </div>
            <!-- end 왼쪽 -->
            <!-- 오른쪽 -->
            <div class="rignt_c">
                <div class="edPros">
                    <div class="mimititle"><b>등록된 상품 관리</b></div>
                    {% if products %}
                        {% for pro in products %}
                        
                            <div class="ppobox">
                                {% if pro.Thumbnail %}
                                <div class="ppoThumb"><img src="../../..{{pro.Thumbnail.url}}" style="width: 100%;height: 100%;"></div>
                                {% else %}
                                <div class="ppoThumb"><img src="{% static 'img/ThumbnailSOT.png' %}"></div>
                                {% endif %}
                                <!-- Thumbnail -->
                                <div class="ppoInfo">
                                    <div class="ppIname"><b>{{pro.name}}</b></div>
                                    <div class="ppoInfoIn">
                                        <div class="ppoInfoInIn">
                                            <span>{{pro.category}}</span>
                                            <img src="{% static 'img/star 8.svg' %}" alt="">
                                            <span>{{pro.price}} / {{pro.amount}}</span>
                                        </div>
                                        <img src="{% static 'img/75.svg' %}" alt="">
                                    </div>
    
                                </div>
                            </div>
                        
                        {% endfor %}
                    {% else %}
                        등록된 상품이 없습니다.
                    {% endif %}
                </div>
                <!-- productsend -->
                <div class="regiPro">
                    <div class="mimititle"><b>상품등록</b></div>
                    <div class="Pro_form">
                        <form action="{% url 'ownerApp:productManage' store.pk %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="Tbutton">
                                <input type="text" name="name" required placeholder="상품명" style="width: 350px;">
                                <button type="submit" id="Kai">상품등록</button>
                            </div><br>
                            이미지등록 <input type="file" name="Thumbnail"><br><br>
                            상품카테고리
                            <select name="category" required>
                                <option value="과일">과일</option>
                                <option value="채소/야채">채소/야채</option>
                                <option value="곡류">곡류</option>
                                <option value="기타">기타</option>
                            </select><br><br>
                            예상수확량<br>
                            <input type="text" name="expect"><br><br>
                            판매가<br>
                            <input type="number" required name="price"> 원 / <input type="text" name="amount"> (기준량)<br><br>
                            예상수확시기<br>
                            <input type="date" name="expectD1" required> ~ <input type="date" name="expectD2" required><br><br>
                            배송가능기간<br>
                            <input type="date" name="deliveryD1" required> ~ <input type="date" name="deliveryD2" required><br><br>
                            포장방식
                            <select name="deliveryOption" required>
                                <option value="아이스팩">아이스팩</option>
                                <option value="신선배송가방">신선배송가방</option>
                            </select><br><br>
                            출하지역<br>
                            <input type="text" name="region" style="width: 300px;"><br><br>
                            소개글<br><textarea name="intro_text" style="width: 350px;"></textarea><br>
                        </form>
                    </div>
                </div>
            </div>
            <!-- end오른쪽 -->
        </div>
        <!--bigcontainer  -->
        <div class="zz">
            <img src="{% static 'img/zz.png' %}">
        </div>
    </div>
    
</body>

WEB/baroProject/ownerApp/templates/ownerApp/productManage.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}

{% block content2 %}
    <h1>상품 등록/관리</h1>
    <br>
    <h4>HElloWorld<h4>
{% endblock %}

{% block content %}
<div style="background-color: aliceblue;">
    <form action="{% url 'ownerApp:productManage' storepk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit">상품등록</button><br>
        상품명 : <input type="text" name="name" required><br>
        이미지등록 : <input type="file" name="Thumbnail"><br>
        상품카테고리 :
        <select name="category" required>
            <option value="과일">과일</option>
            <option value="채소/야채">채소/야채</option>
            <option value="곡류">곡류</option>
            <option value="기타">기타</option>
        </select><br>
        예상수확량 : <input type="text" name="expect"><br>
        가격 : <input type="number" required name="price"> 원 / <input type="text" name="amount"> (기준량)<br>
        예상수확시기 : <input type="date" name="expectD1" required> ~ <input type="date" name="expectD2" required><br>
        배송가능기간 : <input type="date" name="deliveryD1" required> ~ <input type="date" name="deliveryD2" required><br>
        포장방식 : 
        <select name="deliveryOption" required>
            <option value="아이스팩">아이스팩</option>
            <option value="신선배송가방">신선배송가방</option>
        </select>
        출하지역 : <input type="text" name="region"><br>
        소개글 : <textarea name="intro_text"></textarea><br>
    </form>
</div>
{% endblock %}

WEB/baroProject/ownerApp/templates/ownerApp/register.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% endblock %}

{% block content %}
    <h1>ownerApp 판매자 등록</h1>
    사업자등록<br>
    본인인증 -> 이미지로 대체
    <a href="{% url 'ownerApp:register2' %}">다음(확인)</a>

{% endblock %}

WEB/baroProject/ownerApp/templates/ownerApp/register2.html
{% extends 'ownerbase.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'ownerApp/register2.css' %}" type="text/css">
{% endblock %}

{% block content2 %}
<h1>스토어 정보를 입력해주세요</h1>
<br><br>
<h4>
    스토어 개설에 필요한 기본정보를 입력해주세요. 입력한 정보는 내 스토어에서 볼 수 있습니다.
</h4>
{% endblock %}

{% block content %}
    <section class="login">
    <h2>스토어 정보 입력</h2>
    <form action="{% url 'ownerApp:register2' %}" method="POST">
        {%csrf_token%}
        <ul>
            <div class="line1">
        <li>스토어이름
        <input type="text" name="store_name" required><br></li>
        <li>스토어 url
        <input type="text" name="store_url" required><br></li>
        <li>소개글
        <input type="text" name="store_intro" required><br></li>
        <li>고객센터 전화번호
        <input type="text" name="store_tel" required><br></li>
        <li>상품 카테고리
        <select name="category" required>
            <option value="채소/야채">채소/야채</option>
            <option value="과일">과일</option>
            <option value="곡류">곡류</option>
        </select><br></li>
    </div><!--line1-->
    <div class="line2">
        <li>배송정보 입력
        <input type="text" name="store_address" required><br></li>
        <li>정산 입금 계좌
        <select name="bank" required>
            <option value="농협">농협</option>
            <option value="국민">국민</option>
            <option value="신한">신한</option>
            <option value="기타">기타</option>
        </select></li>
        <li><input type="text" name="account_name" required placeholder="예금주명"/></li>
        <li><input type="text" name="store_account" required placeholder="계좌번호"><br></li>
    </div>
        <div class="button1">
        <li><button type="submit"><h5>스토어 개설</h5></button></li>
    </div>
    </form>

</ul>
</section>

{% endblock %}

WEB/baroProject/ownerApp/templates/ownerApp/register3.html
{% extends 'ownerbase.html' %}
{% load static %}

{% block style %}
<style>
    .background{
    /* background-color:#F5F5F5; */
    background-image: url('../../../static/img/finish.jpg');
    width:1920px;
    height:1500px;
    margin-top:-550px;
    background-repeat: no-repeat;
}
.front{
    margin-left:800px;
    padding-top:650px
    
}
</style>
{% endblock %}

{% block content %}
        <div class="background">
            <div class="back">
                
                <!-- 스토어 이름 : {{store.store_name}} -->
                <div class="front">
                    <a href="{% url 'ownerApp:manage' %}"><img src="{% static 'img/finish button.png' %}"></a>
                </div>
            </div>
            
        </div>
    </div>
    

{% endblock %}