WEB/baroProject/accountApp/urls.py
from django.urls import path
from . import views

app_name = 'accountApp'

urlpatterns = [
    path('login/<int:usertype>', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/<int:usertype>', views.signup, name='signup'),
    path('signupAgree/', views.signupAgree, name="signupAgree"),
    path('signupSuccess/', views.signupSuccess, name="signupSuccess"),
]

WEB/baroProject/baroProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userApp.urls')),
    path('accountApp/', include('accountApp.urls')),
    path('ownerApp/', include('ownerApp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/baroProject/userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name="main"),
    path('store/', views.store, name="store"),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('addCart/<int:object_pk>', views.addCart, name='addCart'),
    path('cart/', views.cart, name='cart'),
    path('pay/', views.pay, name='pay'),
    path('accFinish', views.accFinish, name="accFinish"),
]

WEB/baroProject/userApp/models.py
from django.db import models
from django.contrib.auth.models import User
from ownerApp.models import Product
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

class Restaurant(models.Model):
    name = models.CharField(max_length=30)
    style = models.CharField(max_length=30)
    review = models.IntegerField()
    star = models.FloatField()
    
    def __str__(self):
        return f'{self.pk} : {self.name} | {self.style}'

class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    od_amount = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    od_date = models.DateField()
    # DELIERY=[("icepack","아이스팩"), ("premium", "신선배송가방")]
    od_deliopt = models.CharField(max_length=30)
    od_requests=models.TextField(null=True)

    #https://dev-mht.tistory.com/147
    def sub_total(self):
        return int(self.product.price * self.od_amount)

    def __str__(self):
        return f'{self.products} - {self.od_amount} : {self.sub_total}'

WEB/baroProject/userApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from ownerApp.models import Product
from .models import CartItem
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'userApp/home.html')

def main(request):
    context={}
    products = Product.objects.all()[:3]
    context['products'] = products
    return render(request, 'userApp/main.html',context)

def detail(request, pk):
    object = Product.objects.get(pk=pk)

    context={
        'object' : object,
    }
    return render(request, 'userApp/detail.html', context)

@login_required
def addCart(request, object_pk):
    if request.method == "POST":
        print("POST로 들어왔니")
        item = CartItem.objects.create(
            user = User.objects.get(username = request.user.get_username()) ,
            product = Product.objects.get(pk = object_pk),
            od_amount = request.POST['od_amount'],
            od_date = request.POST['od_date'],
            od_deliopt = request.POST['od_deliopt'],
            # od_requests = request.POST['od_requests'],
        )
        print("아이템 생성 완료")
        return redirect('userApp:cart')
        return redirect('cart')
    else:
        print("GET요청")
        return HttpResponse("addCart GET 오류")

def cart(request):
    context={}
    total = 0
    shippingFee = 0

    cart_items = CartItem.objects.filter(user__id = request.user.pk)
    if cart_items.count() == 0:
        context['error'] = '담긴 상품이 없습니다.'
    else:
        for item in cart_items:
            total += item.sub_total()

    pay = total + shippingFee

    context['total'] = total
    context['shippingFee'] = shippingFee
    context['pay'] = pay
    context['cart_items'] = cart_items
    return render(request, 'userApp/Cart.html', context)

def pay(request):
    context={}
    # context['pay'] = pay
    return render(request, 'userApp/pay.html', context)

def store(request):
    context={}

    if request.method == "POST":
        sText = request.POST['searchText']
        context['sText']=sText
        #여자 #10대 #피곤
        gender, age, health = sText.split(' ')
        gender = gender.replace('#', '')
        age = age.replace('#', '')
        health = health.replace('#', '')

        FITERLIST=[(1, '-age1_M_B'),(2, '-age1_M_W'),(3, '-age1_M_G'),
                    (4, '-age1_W_B'),(5, '-age1_W_W'),(6, '-age1_W_G'),
                    (7, '-age2_M_B'),(8, '-age2_M_W'),(9, '-age2_M_G'),
                    (10, '-age2_W_B'),(11, '-age2_W_W'),(12, '-age2_W_G'),
                    (13, '-age3_M_B'),(14, '-age3_M_W'),(15, '-age3_M_G'),
                    (16, '-age3_W_B'),(17, '-age3_W_W'),(18, '-age3_W_G'),
                    (19, '-age4_M_B'),(20, '-age4_M_W'),(21, '-age4_M_G'),
                    (22, '-age4_W_B'),(23, '-age4_W_W'),(24, '-age4_W_G'),]
        

        #나이 
        if age=="10대":
            if gender=="여자":
                if health=="good":
                    fkey=FITERLIST[6-1][1]
                elif health=="worry":
                    fkey=FITERLIST[5-1][1]
                elif health=="bad":
                    fkey=FITERLIST[4-1][1]
            elif gender=="남자":
                if health=="good":
                    fkey=FITERLIST[3-1][1]
                elif health=="worry":
                    fkey=FITERLIST[2-1][1]
                elif health=="bad":
                    fkey=FITERLIST[1-1][1]
        elif age=="20대" or age=="30대":
            if gender=="여자":
                if health=="good":
                    fkey=FITERLIST[12-1][1]
                elif health=="worry":
                    fkey=FITERLIST[11-1][1]
                elif health=="bad":
                    fkey=FITERLIST[10-1][1]
            elif gender=="남자":
                if health=="good":
                    fkey=FITERLIST[9-1][1]
                elif health=="worry":
                    fkey=FITERLIST[8-1][1]
                elif health=="bad":
                    fkey=FITERLIST[7-1][1]
        elif age=="40대" or age=="50대":
            if gender=="여자":
                if health=="good":
                    fkey=FITERLIST[18-1][1]
                elif health=="worry":
                    fkey=FITERLIST[17-1][1]
                elif health=="bad":
                    fkey=FITERLIST[16-1][1]
            elif gender=="남자":
                if health=="good":
                    fkey=FITERLIST[15-1][1]
                elif health=="worry":
                    fkey=FITERLIST[14-1][1]
                elif health=="bad":
                    fkey=FITERLIST[13-1][1]
        elif age == "60대":
            if gender=="여자":
                if health=="good":
                    fkey=FITERLIST[24-1][1]
                elif health=="worry":
                    fkey=FITERLIST[23-1][1]
                elif health=="bad":
                    fkey=FITERLIST[22-1][1]
            elif gender=="남자":
                if health=="good":
                    fkey=FITERLIST[21-1][1]
                elif health=="worry":
                    fkey=FITERLIST[20-1][1]
                elif health=="bad":
                    fkey=FITERLIST[19-1][1]
        else :
            #전체판매량
            fkey = '-salesRate'

        print(fkey)
        products = Product.objects.all().order_by(fkey)[:9]
        context['products'] = products
        print(products)
        print("POST")
        return render(request, 'userApp/store.html', context)
    else :
        products = Product.objects.all()[:9]
        context['products'] = products
        return render(request, 'userApp/store.html', context)

def accFinish(request):
    return render(request, 'userApp/accFinish.html')

WEB/baroProject/userApp/templates/userApp/accFinish.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'userApp/accFinish.css' %}" type="text/css">
{% endblock %}


{% block content %}
<div class="background">
    <div class="finish2">
        <img src="{% static 'img/finish2.png' %}">
    </div>
    <div class="finish1">
        <img src="{% static 'img/finish1.png' %}">
    </div>
    <div class="finish3">
        <a href="{% url 'userApp:main' %}"><img src="{% static 'img/return.svg' %}"></a>
    </div>
    

</div>
{% endblock %}

WEB/baroProject/userApp/templates/userApp/cart.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'userApp/cart.css' %}" type="text/css">
{% endblock %}


{% block content %}
<div class="backcolor">
    <div class="icon">
        <img src="{% static 'img/cart icon1.svg' %}">
        <h1>장바구니</h1>
    </div>
    <div class="zz_container">
        <div class="farmname">
            <a href="#"><img src=""></a>
        </div>
        {% if error %}
            <div>장바구니에 담긴 상품이 없습니다.</div>
        {% else %}
            {% for item in cart_items %}
            <div class="backcolors">
                <!-- 체크박스 -->
                <div class="bar">
                    <img src="{% static 'img/ss.svg' %}">
                </div>
                <!-- 썸네일 -->
                <div class="rice">
                    {% if item.product.Thumbnail %}
                    <a href="#"><img src="../../..{{item.product.Thumbnail.url}}"></a>
                    {% else %}
                    <a href="#"><img src="{% static 'img/ThumbnailSOT.png' %}"></a>
                    {% endif %}

                </div>
                <div class="infocontainer">
                    <div class="category">
                        {{item.product.category}}
                    </div>
                    <div class="newname">
                        <div class="title_new">
                            <h1>{{item.product.name}}</h1>
                        </div>
                        <div id = "newamount">{{item.product.amount}}</div>
                    </div>
                    <div class="price">
                        <h1>{{item.sub_total}}원</h1>
                    </div>
                    <div class="as">
                        <h1>선택옵션: {{item.od_date}} 이후 발송, {{item.od_deliopt}}배송</h1>
                    </div>
                    <div class="count">
                        {{item.od_amount}}개
                    </div>
                </div>
                <!-- 퍼센트 이미지 -->
                <div class="reserve">
                    <img src="{% static 'img/75.svg' %}">
                </div>
            </div>
            {% endfor %}
        {% endif %}
        <div class="accountContainer">
             <!--account-->
            <div class="carttt">
                <img src="{% static 'img/pay.png' %}">
                <div class="v">
                    <h1>{{total}}원</h1>
                </div>
                <div class="b">
                    <h1>{{shippingFee}}원</h1>
                </div>
                <div class="n">
                    <h1>{{pay}}원</h1>
                </div>
                </div>
                <div class="btn_containerPay">
                    <a href="#"><img src="{% static 'img/white.svg' %}"></a>
                    <a href="{% url 'userApp:pay' %}"><img src="{% static 'img/blue.svg' %}"></a>
                </div>
                
            </div>
    </div>
   
        
{% endblock %}

WEB/baroProject/userApp/templates/userApp/detail.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'userApp/detail.css' %}">
{% endblock %}

{% block content %}
    <div class="background">
        <div class="maininfocontainer">
            <!-- 썸네일 -->
            <div class="rice">
                {% if object.Thumbnail %}
                <img src="../../..{{object.Thumbnail.url}}" style="width: 100%;height: 100%;">
                {% else %}
                <img src="{% static 'img/ThumbnailSOT3.png' %}">
                {% endif %}
            </div>
            <!-- 인포 -->
            <div class="mainmaininfo">
                <div class="opt">
                    <div class="category">
                        {{object.category}}
                    </div>
                    <img src="{% static 'img/heart.svg' %}">
                </div>
                <div class="mainnames">
                    <div class="title_z">
                        <h1>{{ object.name }}</h1>
                   </div>
                   <b> {{object.amount}}</b>
                </div>
                <img src="{% static 'img/ththth.png' %}" style="padding-top: 10px;">
                <div class="mbinfo">
                    <div class="mbinfo2">
                        <img src="{% static 'img/star 8.svg' %}" style="width: 100px;">
                        <div class="price">
                            <h1>{{ object.price }}원</h1>
                       </div>
                       <b>{{object.deliveryOption}}</b>
                       <div class="mbinfo3">
                            <div class="reee">
                                {{object.deliveryD1  | date:'y/n/j' }} ~ {{object.deliveryD2 | date:'y/n/j' }}
                            </div>
                            <img src="{% static 'img/reserve short.png' %}">
                       </div>

                    </div>
                    <div class="reserve">
                        <img src="{% static 'img/75.svg' %}">
                   </div>
                    
                </div>

            </div>
        </div>
        <!--  -->
        <div class="first">
            <ul class="three">
                <li><img src="{% static 'img/graph.png' %}">
                </li>
                <li> 
                    <form action="{% url 'userApp:addCart' object.pk %}" method="POST">
                        {% csrf_token %}
                        <img src="{% static 'img/three square.svg' %}">
                        <h2>{{ object.price }}원</h2>
                        <!-- <h3>{{object.amount}} - </h3>
                        <span id="input_a"><input type="date" name="od_date" min={{object.deliveryD1}}, max={{object.deliveryD2}} required>개</span><br>
                        <h5>*희망 발송일 설정은 예상 배송 기간 이후로 설정 가능합니다.</h5>
                        <span id="input_b"><input type="number" name="od_amount" min = 1 required></span><br>
                        <h7><img src="{% static 'img/reserve long.png' %}" alt="예약"></h7>
                        <h8><button type = submit><img src="{% static 'img/cart button.png' %}" alt="장바구니"></button></h8>
                        <input type="hidden" name="od_deliopt" value={{object.deliveryOption}} > -->
                        <span class="hot">{{object.amount}} : </span> 
                        <span id="input_a"><input type="number" name="od_amount" min = 1 required>개</span><br><br>
                        <span><img src="{% static 'img/check_blue.svg' %}" alt="">택배 배송</span>
                        <span><img src="{% static 'img/check_gray.svg' %}">직거래</span><br><br>
                        <span>*희망 발송일 설정은 예상 배송 기간 이후로 설정 가능합니다.</span><br><br>
                        <span id="input_b">희망배송일 :<input type="date" name="od_date" min={{object.deliveryD1}}, max={{object.deliveryD2}} required> </span><br><br>
                        <span><img src="{% static 'img/reserve long.png' %}" alt="예약"></span>
                        <span><button type = submit style="border-color:white;"><img src="{% static 'img/cart button.png' %}" alt="장바구니"></button></span>
                        <input type="hidden" name="od_deliopt" value={{object.deliveryOption}} >
                    </form>
                </li>
            </ul>
        </div>
        <div class="second">
            <img src="{% static 'img/second.png' %}">
        </div>
        <div class="page">
            <img src="{% static 'img/page.png' %}">
        </div>
    </div>

{% endblock %}

WEB/baroProject/userApp/templates/userApp/home.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="../../static/userApp/home.css" type="text/css">
{% endblock %}

{% block content2 %}
<h1>회원 유형을 선택해 주세요</h1>
<br><br>
<h4>유형을 선택하시면 솥에서 제공하는 다양한 서비스를 이용하실 수 있습니다.</h4>
{% if error %} <br>{{ error }} {% endif %}
{% endblock %}

{% block content %}
    
    <ul class="icons">
        <li>
             <div class="icon_img"></div>
             <div class="content_bold"><a class="name" href="{%  url 'accountApp:login' 1 %}">판매자</a></div>
             <i class="fas fa-minus"></i>
             <div class="content2">판매자는 솥을 통해 수요량을 조사하고, 신선한 농작물을 판매할 수 있습니다.</div>
         </li>

        
        <li>
             <div class="icon2_img"></div>
             <div class="content_bold"><a class="name" href="{%  url 'accountApp:login' 2 %}">구매자</a></div>
             <i class="fas fa-minus"></i>
             <div class="content2">구매자는 솥을 통해 간편하게 농작물을 주문하고, 갓 생산된 농작물을 받아보실 수 있습니다.</div>
         </li>
    </ul>
 
{% endblock %}

WEB/baroProject/userApp/templates/userApp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>솥 by SSAK3</title>
    <script src="https://kit.fontawesome.com/b0f29e9bfe.js" corssorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="../../static/userApp/main.css">
</head>

<body>
    <div class="wrap">
        <div class="intro">
            <div class="header">
                <ul class="nav">
                    <li><a href="{% url 'userApp:main' %}"><img src="../../../static/img/SOT_logo.png"></a></li>
                    <li><a href="{% url 'userApp:store' %}">스토어</a></li>
                    <li><a href="#">커뮤니티</a></li>
                    <li><a href="#">고객센터</a></li>
                </ul>
                <ul class="searcharea">
                    <li><input type="search" placeholder="Serach.."></li>
                    <li><a href="{% url 'userApp:cart' %}"><img src="../../../static/img/cart.svg"></a></li>
                    <li><a href="{% url 'userApp:home' %}"><img src="../../../static/img/mypage.svg"></a></li>
                </ul>
            </div>
        </div>
    </div>
    <!--2-->
    <div class="main_text0">
        <ul>
            <li><div class="q">SHOPPING</div></li>
            <li><div class="w">금주의 주문량 TOP3</div></li>
            <li><div class="e">이번 주 회원님들이 가장 많이 찾은 식품을 만나보세요!</div></li>
        </ul>
        <div class="maincontainer">
            <ul  class="icon4">
                <!-- <li>
                    <div class="tomato5">
                        <a href="">
                            <div class="image1">
                                <img src="../../../static/img/tomato1.png" alt=""><br></div>
                            <div class="name">
                                <div class="title">
                                    <div id1="minititle">무농약 방울토마토</div></div>
                                <div class="miniamount">
                                    <div id2="miniamount">2kg/팩</div></div>
                            </div>
                            <div class="star">
                                <img src="../../../static/img/star.svg" alt=""></div>
                            <div class="price">
                                <div class="price1">
                                    <div>10, 900원</div></div>
                                <div class="reserve1">
                                    <div><img src="../../../static/img/reserve.svg"></div></div>
                            </div>
                         </a>
                
                    </div>
                </li> -->
                {% for pro in products%}
                <li>
                    <div class="tomato5">
                        <a href="{% url 'userApp:detail' pro.pk %}">
                            <div class="image1">
                                {% if pro.Thumbnail == null %}
                                <img src="../../../static/img/ThumbnailSOT.png" style="width: 342px;height: 249px;" alt=""><br></div>
                                {% else %}
                                <img src="../../..{{pro.Thumbnail.url}}" style="width: 342px;height: 249px;" alt=""><br></div>
                                {% endif %}
                            <div class="name">
                                <div class="title_z">
                                    <div id1="minititle">{{pro.name}}</div></div>
                                <div class="miniamount">
                                    <div id2="miniamount">{{pro.amount}}</div></div>
                            </div>
                            <div class="star">
                                <img src="../../../static/img/star 8.svg" alt=""></div>
                            <div class="price">
                                <div class="price1">
                                    <div>{{pro.price}}원</div></div>
                                <div class="reserve1">
                                    <div><img src="../../../static/img/75.svg"></div></div>
                            </div>
                        </a>
                    </div>
                </li>
                {% endfor %}
                <!-- <li>
                    <div class="tomato5">
                        <a href="">
                            <div class="image1">
                                <img src="../../../static/img/cheese5.png" alt=""><br></div>
                            <div class="name">
                                <div class="title">
                                    <div id1="minititle">임실 구워먹는 우리치즈</div></div>
                                <div class="miniamount">
                                    <div id2="miniamount">280g/팩</div></div>
                            </div>
                            <div class="star">
                                <img src="../../../static/img/star9.svg" alt=""></div>
                            <div class="price">
                                <div class="price1">
                                    <div>10, 600원</div></div>
                                <div class="reserve1">
                                    <div><img src="../../../static/img/62.svg"></div></div>
                            </div>
                        </a>
                    </div>
                </li> -->
            </ul>  
        </div>
    </div>

    <div class="main_text1">
    </div>

    <!--4-->
    <div  class="main_text2">
        <ul>
            <li><div class="z">STORE</div></li>
            <li><div class="x">신뢰도 최고 인기농장 TOP2</div></li>
            <li><div class="c">믿고 사 먹을 수 있는 재구매율 최상위 농장을 만나보세요!</div></li>
        </ul>
        
        <ul class="icons">
            <li><a href="#"><img src="../../../static/img/farm1.png"></a></li>
            <li><a href="#"><img src="../../../static/img/farm2.png"></a></li>
        </ul>
    
    </div>
    <!--5-->
    <div class="gray">
        <div class="ld">
            <a href="#"><img src="../../../static/img/jj.png"></a>
        </div>
    </div>
    <!--하단 정보바-->
   <div class="zz"><img src="../static/img/zz.png"></div>
</body>

WEB/baroProject/userApp/templates/userApp/pay.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'userApp/pay.css' %}" type="text/css">
{% endblock %}

{% block content2 %}
{% endblock %}

{% block content %}
<!--main-->
    <div class="background">
        
        <div class="navi">
            <img src="{% static 'img/finish_nav.png' %}">
        </div>
        <ul class="icon">
            <li><img src="{% static 'img/finish_order.png' %}">
               <div class="category2">
                <img src="{% static 'img/optbutton.png' %}">
                <h1>곡식</h1>
               </div>
               <div class="name">
               <h2>유기농 우리쌀 도정예약</h2>
                <h3>10kg (kg당 3,200원)</h3>
                <h4>선택옵션: 2021년 8월 24일 이후 발송, 택배 배송(진공포장)</h4>
                <h5>32,000원</h5>
            </div>
            </li><!--첫번째ul-->
            
            <li><img src="{% static 'img/finish_confirm.png' %}">
                <div class="price1">
                    <h6>9,600원</h6>
                  
                 
                <div class="credit">
                    <a href="{% url 'userApp:accFinish' %}"><img src="{% static 'img/credit.png' %}"></a>
                </div>
                <div class="pprice">
                    <h7>9,600원</h7>
                </div>
                <div class="ppprice">
                    <h8>+0원</h8>
                </div>
            </li>
        </ul>


    </div><!--회색background-->

{% endblock %}

WEB/baroProject/userApp/templates/userApp/store.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'userApp/store.css' %}">
{% endblock %}

{% block content %}

<!--임시-->
<div class="second">
    <div><img src="{% static 'img/t.png' %}"></div>
    <div class="sss5">
        <form action="{% url 'userApp:store' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="searchText" class="searchArea" placeholder="#여자 #20대 #피곤 ">
            <button type="submit" id="search">검색</button>
        </form>
    </div>
    
</div>
<div class="third">
    {% if sText %}
    {{sText}} 의 판매량 순 결과입니다.
    {% endif %}
</div>




<!--2-->
<div class="page">
    <div class="sCbox">
        {% for pro in products %}
        <div class="tomato5">
            <a href="{% url 'userApp:detail' pro.pk %}">
                <div class="image1">
                    {% if pro.Thumbnail  %}
                    <img src="../../..{{pro.Thumbnail.url}}" style="width: 342px;height: 249px;" alt=""><br></div>
                    {% else %}
                    <img src="../../../static/img/ThumbnailSOT.png" style="width: 342px;height: 249px;" alt=""><br></div>
                    
                    {% endif %}
                <div class="name">
                    <div class="title_z">
                        <div id1="minititle">{{pro.name}}</div></div>
                    <div class="miniamount">
                        <div id2="miniamount">{{pro.amount}}</div></div>
                </div>
                <div class="star">
                    <img src="../../../static/img/star 8.svg" alt=""></div>
                <div class="price">
                    <div class="price1">
                        <div>{{pro.price}}원</div></div>
                    <div class="reserve1">
                        <div><img src="../../../static/img/75.svg"></div></div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>


    <ul class="icon">
        <li><a href="#"><img src="{% static 'img/tomato.png' %}"></a></li>
        <li><a href="#"><img src="{% static 'img/rice.png' %}"></a></li>
        <li><a href="#"><img src="{% static 'img/egg.png' %}"></a></li>

    </ul>
    <ul class="icon1">
        <li><div class="rice"><a href="#"><img src="{% static 'img/mushroom.png' %}"></a></div></li>
        <li><div class="cheese"><a href="#"><img src="{% static 'img/oil.png' %}"></a></div></li>
        <li><div class="tomato"><a href="#"><img src="{% static 'img/cheese.png' %}"></a></div></li>

    </ul>
    <ul class="icon2">
        <li><div class="rice2"><a href="#"><img src="{% static 'img/melon1.png' %}"></a></div></li>
        <li><div class="cheese2"><a href="#"><img src="{% static 'img/account1.png' %}"></a></div></li>
        <li><div class="tomato2"><a href="#"><img src="{% static 'img/apple.png' %}"></a></div></li>

    </ul>

</div>
{% endblock %}