WEB/baroProject/accountApp/urls.py
from django.urls import path
from . import views

app_name = 'accountApp'

urlpatterns = [
    path('login/<int:usertype>', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/<int:usertype>', views.signup, name='signup'),
    path('signupAgree/', views.signupAgree, name="signupAgree"),
    path('signupSuccess/', views.signupSuccess, name="signupSuccess"),
]

WEB/baroProject/baroProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userApp.urls')),
    path('accountApp/', include('accountApp.urls')),
    path('ownerApp/', include('ownerApp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/baroProject/userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name="main"),
    path('store/', views.store, name="store"),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('addCart/<int:object_pk>', views.addCart, name='addCart'),
    path('cart/', views.cart, name='cart'),
    path('pay/', views.pay, name='pay'),
    path('accFinish', views.accFinish, name="accFinish"),
]

WEB/baroProject/accountApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class info(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    usertype=models.CharField(max_length=30)

    def __str__(self):
        return f'{self.pk} : {self.user} : {self.usertype}'
    

WEB/baroProject/accountApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from .models import info

# Create your views here.

def signup(request, usertype):
    context={}
    # POST Method
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        password_check = request.POST['password_check']
        usertype = request.POST['usertype']

        # 제대로 입력되었을 경우
        if (username and password and password_check == password):
            new_user = User.objects.create_user(
                username = username,
                password = password,
            )
            new_info=info.objects.create(
                user=User.objects.get(username = username),
                usertype = request.POST['usertype'],
                )

            return redirect('accountApp:signupSuccess')
        else:
            context['error'] = "아이디와 비밀번호를 다시 확인해주세요."

    # GET Method
    context['usertype'] = usertype
    return render(request, 'accountApp/signup.html', context)


def login(request, usertype):
    context={}

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        usertype = int(request.POST.get('usertype', ''))
        if username and password:
            user = auth.authenticate(
                request,
                username = username,
                password = password
            )
            if user is not None:
                # 사용자가 있으면 로그인후 home으로
                auth.login(request, user)
                ut = int(info.objects.get(user=user).usertype)
                # if (ut =="판매자" or ut==1): ut = 1
                # elif ut =="구매자" or ut ==2 : ut=2
                if ut != usertype:
                    auth.logout(request)
                    context['error'] = "로그인 유형을 다시 선택하세요."
                    print("유저홈")
                    return redirect('userApp:home')
                elif usertype == 1: #생산자
                    print("생산자 manage")
                    return redirect('ownerApp:manage')
                elif usertype == 2: #소비자
                    print("유저홈")
                    return redirect('userApp:main')
            else:
                print("에러1")
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'
        else:
            #아이디나 비밀번호가 제대로 입력되지 않았을때
            print("에러2")
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'

    # Get Method
    print("설마여기")
    print(usertype)
    context['usertype'] = usertype
    return render(request, 'accountApp/login2.html', context)

def logout(request):
    if request.method == "POST":
        auth.logout(request)
    # 로그아웃하면 이전 페이지로
    #return redirect(request.POST['path'])
    # 로그아웃하면 홈으로
    return redirect("userApp:home")
   

def signupAgree(request):
    return render(request, 'accountApp/signupAgree.html')

def signupSuccess(request):
    return render(request, 'accountApp/signupSuccess.html')

WEB/baroProject/accountApp/templates/accountApp/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

    <link rel="stylesheet" href="{% static 'accountApp/login.css' %}" type="text/css"> 
{% endblock %}

{% block content %}
    {% if error %}
    <div>
        {{ error }}
    </div>
    {% endif %}
    <h1>{% if usertype == 1 %}생산자 {% elif usertype == 2 %}소비자 {% endif %}로그인 페이지 입니다.</h1>
    <div>
        {{usertype}}
        {% if usertype == 1 %}
        <form action="{% url 'accountApp:login' 1 %}" method="POST">
        {% elif usertype == 2 %}
        <form action="{% url 'accountApp:login' 2 %}" method="POST">  
        {% endif %}
            {% csrf_token %}
            <h3>LOGIN</h3>
            <div>
                <label class='log_lb' for="username">아이디</label>
                <input type="text" id = 'username' placeholder="아이디" name="username">
            </div>
            <div >
                <label class='log_lb' for="password">비밀번호</label>
                <input type="password" id='password' placeholder="비밀번호" name="password">
            </div>
            {% if usertype == 1 %}
                <input type= "hidden" name="usertype" value=1>
            {% elif usertype == 2 %}
                <input type= "hidden" name="usertype" value=2>    
            {% endif %}
            <button type="submit">로그인</button>
        </form>
        <div>
            Don't have account?
            <a href="{% url 'accountApp:signupAgree' %}">Signup Now</a>
        </div>
    </div>
{% endblock %}

WEB/baroProject/accountApp/templates/accountApp/login2.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'accountApp/login.css' %}" type="text/css"> 
    <!-- <link rel="stylesheet" type="text/css" href="login2.css"> -->
    <style>
        .main_text0{
    top: 747px;
    width: 1915px;
    height: 500px;
    /* background: transparent url('../static/img/square.svg') 0% 0% no-repeat padding-box; */
    background-color: #F5F5F5;
    opacity: 1;}
    </style>
{% endblock %}

{% block content2 %}
<h1 style="font-size: 70px;">로그인</h1>
<br><img src="{% static 'img/사각형 22.png' %}"><br><br>
    {% if error %}
    <div>
        {{ error }}
    </div>
    {% endif %}
    <!-- <h1>{% if usertype == 1 %}생산자 {% elif usertype == 2 %}소비자 {% endif %}로그인 페이지 입니다.</h1> -->

    <div>
        {% if usertype == 1 %}
        <form action="{% url 'accountApp:login' 1 %}" method="POST">
        {% elif usertype == 2 %}
        <form action="{% url 'accountApp:login' 2 %}" method="POST">  
        {% endif %}
            {% csrf_token %}
           <div class="amount">
               <div class="food">
                    {% if usertype == 1 %}
                    <img src="../../../static/img/produceerlogin.PNG">
                    {% elif usertype == 2 %}
                    <img src="../../../static/img/consumerlogin2.png">
                    {% endif %}
               </div>
               
              
                <div class="service">
                    
                    
                    <ul>  
                        <li><input type="text" id = 'username' placeholder="아이디" name="username"></li>
                        <li><input type="password" id='password' placeholder="비밀번호" name="password"></li>
                        <li><button type="submit">로그인하기</button></li>
                        <div class="account">
                            아직 회원이 아니신가요?
                            <a href="{% url 'accountApp:signupAgree' %}">Signup Now</a>
                        </div>
                    
                    </ul>
                    
                </div>

            </div>
            <div class="logo">
                <img src= "{% static 'img/sot_logo.png' %}"></div>
            {% if usertype == 1 %}
                <input type= "hidden" name="usertype" value=1>
            {% elif usertype == 2 %}
                <input type= "hidden" name="usertype" value=2>    
            {% endif %}
        </form>
    </div>
{% endblock %}

WEB/baroProject/accountApp/templates/accountApp/signup.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
    <!-- <link rel="stylesheet" type="text/css" href="signup.css"> -->
    <link rel="stylesheet" href="{% static 'accountApp/signup.css' %}" type="text/css"> 
{% endblock %}

{% block content2 %}
<h1>회원정보 입력 및 본인인증을 완료해주세요</h1>
<br>
<h4>본인확인을 위한 절차이며, 다른 용도로 사용되지 않습니다.<br>
판매자의 경우 사업자등록 인증을 완료해야 서비스를 이용할 수 있습니다.</h4>
{% endblock %}

{% block content %}
    {% if error %}
    <div>
        {{ error }}
    </div>
    {% endif %}
    <div id='login_box'>
        {% if usertype == 1%}
        <form action="{% url 'accountApp:signup' 1 %}" method="POST">
        {%  elif usertype == 2%}
        <form action="{% url 'accountApp:signup' 2 %}" method="POST">
        {% endif %}
            {% csrf_token %}
            <div class="sign" style="background-color: white;">
                <h3>회원정보 입력</h3>
                <ul class="top">
                <li><label for="username">아이디</label> 
                    <input type="text" id = 'username' placeholder="띄어쓰기 없는 영문, 숫자로만 6~20자" name="username"></li> 
                
                
                <li> <label for="password">비밀번호</label> 
                    <input type="password" id='password' placeholder="띄어쓰기 없는 영문, 숫자, 특수문자로만 8~12자" name="password"></li>
                
                
                    <li><label for="password_check">비밀번호 재확인</label> 
                    <input type="password" id='password_check' placeholder="" name="password_check"></li>
                </ul>
                {% if usertype == 1%}
                <input type="hidden" name='usertype' value=1>
                <div class="cap">
                    <img src="../../../static/img/ga.jpg">
                </div>
                {%  elif usertype == 2%}
                <input type="hidden" name='usertype' value="2">
                <div class="cap">
                    <img src="../../../static/img/consumerAgree.jpg">
                </div>
                {% endif %}
                <div class="bu">
                    <button type="submit">가입하기</button>
                </div>
            </div>
        </form>
        
    </div>
{% endblock %}

WEB/baroProject/accountApp/templates/accountApp/signupAgree.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<style>
    .main_box{
        width:100%;
        height:1600px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    .container{
        top: 686px;
        left: 428px;
        width: 1064px;
        height: 327px;
        background-color: aqua;
         background: transparent url('../../../static/img/agree.png') 0% 0% no-repeat padding-box;
        opacity: 1;

        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;

        color: #FFFFFF;
        font-size:50px;

    }
    .container2{
        width: 1064px;
        height: 1221px;
        /* background: transparent url('img/패스 6.png') 0% 0% no-repeat padding-box; */
        background-color:#FFFFFF;
        box-shadow: 0px 7px 20px #00000029;
        opacity: 1;
        display: flex;
        flex-direction: column;
        /* justify-content: space-around; */
        align-items: center;
    }
    .buttonbox{
        width: 80%;
        display: flex;
        align-items: center;
        justify-content: space-around;

    }
    .btnbox{
        top: 2051px;
        left: 978px;
        width: 327px;
        height: 76px;
        /* background: transparent url('img/사각형 33.png') 0% 0% no-repeat padding-box; */
        background-color: #629DD9;
        box-shadow: 0px 3px 6px #00000029;
        border-radius: 38px;
        opacity: 1;

        display: flex;
        align-items: center;
        justify-content: center;
        color:#FFFFFF;
        font-size: 20px;

    }
    .imgcontainer{
        width: 1000px;
        height: 1000px;
    }
    .main_text0{
    top: 747px;
    width: 1915px;
    height: 1500px;
    /* background: transparent url('../static/img/square.svg') 0% 0% no-repeat padding-box; */
    background-color: #F5F5F5;
    opacity: 1;
}

</style>
{% endblock %}

{% block content2 %}
<h1 style="font-size: 50px;">약관에 동의해 주세요</h1>
<br>
<br>
<h4 style="font-size: 20px;">솥은 사용자의 체계적인 정보 관리를 위해 약관동의를 원칙으로 하고 있습니다. 이용 약관을 읽고 동의하셔야 회원가입 절차가 진행됩니다.</h4>
<br>
<br>
<div class="main_box">
    <div class="container">
       약관 동의<br>
        <img src="../../../static/img/사각형 22.png" alt="" style="padding-top: 20px;">
    </div>
    <div class="container2">
        <div class="imgcontainer" >
            <img id="agree" src="../../../static/img/signupAgreeimage.jpg" alt="이용약관" style="width: 100%;height: 100%;">
        </div>
        <br>
       <div class="buttonbox">
           <a href="{% url 'accountApp:signup' 1 %}"><div class="btnbox">판매자 회원가입</div></a>
           <a href="{% url 'accountApp:signup' 2 %}"><div class="btnbox">구매자 회원가입</div></a>
       </div>
    </div>
   
   </div>
{% endblock %}

{% block content %}

    
{% endblock %}

WEB/baroProject/accountApp/templates/accountApp/signupSuccess.html
{% extends 'base2.html' %}
{% load static %}

{% block style %}
<style>
    .main_box{
        width:100%;
        height:830px;
        display: flex;
        justify-content: center;
    }
    .loginbox{
        display: flex;
        justify-content: center;
        align-items: center;
        color:#FFFFFF;
        border:0;

        top: 571px;
        left: 797px;
        width: 327px;
        height: 76px;
        background: var(--unnamed-color-629dd9) 0% 0% no-repeat padding-box;
        background: #629DD9 0% 0% no-repeat padding-box;
        box-shadow: 0px 3px 6px #00000029;
        border-radius: 38px;
        opacity: 1;


    }

    .re_login{
        top: 597px;
            left: 903px;
            
            font: var(--unnamed-font-style-normal) normal var(--unnamed-font-weight-normal) var(--unnamed-font-size-24)/30px var(--unnamed-font-family-sandoll-gothicneo1);
            letter-spacing: var(--unnamed-character-spacing--0-48);
            color: var(--unnamed-color-ffffff);
            text-align: left;
            font: normal normal normal 24px/30px Sandoll GothicNeo1;
            letter-spacing: -0.48px;
            color: #FFFFFF;
            opacity: 1;
    }
</style>
{% endblock %}

{% block content2 %}
<h1>회원가입이 완료되었습니다.</h1>
<br>
<h4>모든 회원가입절차가 완료되었습니다. 로그인후 이용해 주세요.</h4>
<br><br>
<div class="main_box">
    <div class="loginbox">
        <a class="re_login" href="{% url 'userApp:home' %}">로그인 하기</a>  
    </div> 
</div>

{% endblock %}

{% block content %}

  
{% endblock %}