WEB/baroProject/accountApp/urls.py
from django.urls import path
from . import views

app_name = 'accountApp'

urlpatterns = [
    path('login/<int:usertype>', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/<int:usertype>', views.signup, name='signup'),
    path('signupAgree/', views.signupAgree, name="signupAgree"),
    path('signupSuccess/', views.signupSuccess, name="signupSuccess"),
]

WEB/baroProject/baroProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userApp.urls')),
    path('accountApp/', include('accountApp.urls')),
    path('ownerApp/', include('ownerApp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEB/baroProject/ownerApp/urls.py
from django.urls import path
from . import views

app_name = 'ownerApp'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('manage/', views.manage, name='manage'),
    path('register/', views.register, name='register'),
    path('register2/', views.register2, name='register2'),
    path('register3/<int:store_pk>', views.register3, name='register3'),
    path('help/', views.help, name='help'),
    path('productManage/<int:storepk>', views.productManage, name="productManage"),
]

WEB/baroProject/userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name="main"),
    path('store/', views.store, name="store"),
    path('detail/<int:pk>', views.detail, name='detail'),
    path('addCart/<int:object_pk>', views.addCart, name='addCart'),
    path('cart/', views.cart, name='cart'),
    path('pay/', views.pay, name='pay'),
    path('accFinish', views.accFinish, name="accFinish"),
]

WEB/baroProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>솥 by SSAK3</title>
    <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
    <script src="https://kit.fontawesome.com/b0f29e9bfe.js" corssorigin="anonymous"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
    <div class="wrap">
        <div class="intro_bg">
            <div class="header">
                <ul class="nav">
                    {% if user.is_authenticated %}
                    <!-- 로그인 한 사용자 -->
                    <li>
                        <form action="{% url 'accountApp:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="path" value="{{request.path}}">
                            <button id = logout type = submit>Log out</a>
                        </form>
                    </li>
                    <li><a href="#"><i class="fas fa-bars"></i></a></li>
                    {% else %}
                    <!--로그인 안 한 사용자-->
                    <li><a href="{% url 'userApp:home' %}">Log in</a></li>
                    <li><a href="{% url 'accountApp:signupAgree' %}">Sign up</a></li>
                    <li><a href="#"><i class="fas fa-bars"></i></a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="intro_text">
                {% block content %}
                {% endblock %}
            </div> 
        </div>
    </div>
    <a href="" clasas="navbar_tooglBtn"></a>
    <i class="fas fa-bars"></i>
</body>
</html>

WEB/baroProject/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>솥 by SSAK3</title>
    <link rel="stylesheet" href="{% static 'base2.css' %}" type="text/css">
    <script src="https://kit.fontawesome.com/b0f29e9bfe.js" corssorigin="anonymous"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
    <div class="wrap">
        <div class="intro">
            <div class="header">
                <ul class="nav">
                    <li><a href="{% url 'userApp:main' %}"><img src="{% static 'img/SOT_logo.png' %}"></a></li>
                    <li><a href="{% url 'userApp:store' %}">스토어</a></li>
                    <li><a href="#">커뮤니티</a></li>
                    <li><a href="#">고객센터</a></li>
                </ul>
                <ul class="searcharea">
                    {% if user.is_authenticated %}
                    <!-- 로그인 한 사용자 -->
                    <li>
                        <form action="{% url 'accountApp:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="path" value="{{request.path}}">
                            <button id = logout type = submit>Log out</a>
                        </form>
                    </li>
                    {% endif %}
                    <li><input type="search" placeholder="Serach.."></li>
                    <li><a href="{% url 'userApp:cart' %}"><img src="{% static 'img/cart.svg' %}"></a></li>
                    <li><a href="{% url 'userApp:home' %}"><img src="{% static 'img/mypage.svg' %}"></a></li>
                </ul>
            </div>
            <div class ="title">
                {% block content2 %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!--2-->
    <div class="main_text0">
        {% block content %}
        {% endblock %}
    </div>
    {% block content3 %}
    {% endblock %}
   <!--하단 정보바-->
   <div class="zz"><img src="{% static 'img/zz.png' %}"></div>
</body>

WEB/baroProject/templates/ownerbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>솥 by SSAK3</title>
    <link rel="stylesheet" href="{% static 'base2.css' %}" type="text/css">
    <script src="https://kit.fontawesome.com/b0f29e9bfe.js" corssorigin="anonymous"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
    <div class="wrap">
        <div class="intro">
            <div class="header">
                <ul class="nav">
                    <li><a href="{% url 'userApp:main' %}"><img src="{% static 'img/SOT_logo.png' %}"></a></li>
                    <li><a href="{% url 'ownerApp:manage' %}">내 스토어</a></li>
                    <li><a href="#">커뮤니티</a></li>
                    <li><a href="#">고객센터</a></li>
                </ul>
                <ul class="searcharea">
                    {% if user.is_authenticated %}
                    <!-- 로그인 한 사용자 -->
                    <li>
                        <form action="{% url 'accountApp:logout' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="path" value="{{request.path}}">
                            <button id = logout type = submit>Log out</a>
                        </form>
                    </li>
                    {% endif %}
                    <li><input type="search" placeholder="Serach.."></li>
                    <li><a href="{% url 'userApp:cart' %}"><img src="{% static 'img/cart.svg' %}"></a></li>
                    <li><a href="{% url 'userApp:home' %}"><img src="{% static 'img/mypage.svg' %}"></a></li>
                </ul>
            </div>
            <div class ="title">
                {% block content2 %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!--2-->
    <div class="main_text0">
        {% block content %}
        {% endblock %}
    </div>
    {% block content3 %}
    {% endblock %}
   <!--하단 정보바-->
   <div class="zz"><img src="{% static 'img/zz.png' %}"></div>
</body>